name: giffy_dialog
description: A Flutter package for a quick, handy and beautiful giffy dialog.
version: 1.8.2
homepage: https://github.com/xsahil03x/giffy_dialog

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: